### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by othyn** [olofvndrhr/flox-dockerized#1]
Spent quite a while trying to figure out why Laravel kept creating a new session on every request and failing to auth the session after logging in.

Not sure if it was 100% related, but things started to work correctly when I manally checked all the `env` variables in the repo to find any mismatches, and there was.

`flox_init` is the actual `env` variable required for DB init, so the user is never created. However the documentation currently states `flox_db_init`.

So either the code needs fixing to match the docs (`flox_db_init`), or the docs needs fixing to match the code (`flox_init`) 😄

**Comment by olofvndrhr** [comment]
Hello, and thanks for you issue.
I renamed the variable some time ago and did not update the docs for it, just the example docker-compose file.
I fixed the typo now 😄 

fixed in #368a471

Best regards

**Comment by othyn** [comment]
Fantastic, thank you!

**Comment by PhuriousGeorge** [comment]
Just jumping in to say it would be great to update the var on DockerHub as well

**Comment by olofvndrhr** [comment]
@PhuriousGeorge fixed :)
